name: funk-tree-new

services:
  postgres:
    image: postgres
    container_name: funk-tree-new-postgres
    environment:
      POSTGRES_DB: funk-tree-new
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - funk-tree-new_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  funk-tree-new_postgres_data:
